// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu1mIR1NOyWPUnidWJLv3OBXeim1noAEg',
    appId: '1:231071332960:web:243f1bbf392bd9a92fa105',
    messagingSenderId: '231071332960',
    projectId: 'hashplusapp-dfbcb',
    authDomain: 'hashplusapp-dfbcb.firebaseapp.com',
    storageBucket: 'hashplusapp-dfbcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PfuW1W9XavLGPeKvNGCoFHpnC-u8eFo',
    appId: '1:231071332960:android:f87a40d17e8a3adc2fa105',
    messagingSenderId: '231071332960',
    projectId: 'hashplusapp-dfbcb',
    storageBucket: 'hashplusapp-dfbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjH7fbswc_69mPJXaub5rm0iwERNBi-Es',
    appId: '1:231071332960:ios:a19829e3c06e2db72fa105',
    messagingSenderId: '231071332960',
    projectId: 'hashplusapp-dfbcb',
    storageBucket: 'hashplusapp-dfbcb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjH7fbswc_69mPJXaub5rm0iwERNBi-Es',
    appId: '1:231071332960:ios:a19829e3c06e2db72fa105',
    messagingSenderId: '231071332960',
    projectId: 'hashplusapp-dfbcb',
    storageBucket: 'hashplusapp-dfbcb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu1mIR1NOyWPUnidWJLv3OBXeim1noAEg',
    appId: '1:231071332960:web:c6e1f58ca465f0902fa105',
    messagingSenderId: '231071332960',
    projectId: 'hashplusapp-dfbcb',
    authDomain: 'hashplusapp-dfbcb.firebaseapp.com',
    storageBucket: 'hashplusapp-dfbcb.firebasestorage.app',
  );
}
